name: Update README
on: [push]
#   schedule:
#     - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Readme
      uses: theboi/github-update-readme@v0.1-alpha
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Your GitHub username 
        username: theboi
        title: byetitle
        subtitle: byebye 

# jobs:
#   build:
#     # Job name is Greeting
#     name: Greeting2
#     # This job runs on Linux
#     runs-on: ubuntu-latest
#     steps:
#       # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
#       - name: Hello world
#         uses: actions/hello-world-javascript-action@v1
#         with:
#           who-to-greet: 'Mona the Octocat'
#         id: hello
#       # This step prints an output (time) from the previous step's action.
#       - name: Echo the greeting's time
#         run: echo 'The time was ${{ steps.hello.outputs.time }}.'
